spring:
  application:
    name: movieApi
  datasource:
    url: jdbc:postgresql://localhost:5432/movie-database
    username: postgres
    password: Postgres1234567890
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      .hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true